export const MODULES = [
    "MM (Materials Management)",
    "FI (Financial Accounting)",
    "CO (Controlling)",
    "SD (Sales and Distribution)",
    "PP (Production Planning)",
    "QM (Quality Management)",
    "PM (Plant Maintenance)",
    "WM (Warehouse Management)",
    "EWM (Extended Warehouse Management)",
];

export const SOLUTION_TYPES = [
    "User Guidance + Mandatory Escalation",
    "User Guidance",
];

export const LOG_CATEGORIES = [
    { id: 2726, label: "ABAP" },
    { id: 287815, label: "APEX" },
    { id: 156494, label: "Costing" },
    { id: 2701, label: "Finance , Treasury" },
    { id: 184749, label: "Helpdesk" },
    { id: 18998, label: "IT Infrastructure" },
    { id: 3421, label: "Master Data Maintenance" },
    { id: 2703, label: "Material Management" },
    { id: 152838, label: "Orion" },
    { id: 13185, label: "POWERBI" },
    { id: 2850, label: "Plant Maintenance" },
    { id: 2848, label: "Production" },
    { id: 4469, label: "Quality" },
    { id: 2852, label: "SAP Basis" },
    { id: 4458, label: "SAP GRC" },
    { id: 2847, label: "Sales" },
    { id: 3976, label: "Success Factors-HR" },
    { id: 2849, label: "Transport" },
    { id: 135435, label: "Treasury Management" },
    { id: 2851, label: "WareHouse" },
];

export const LOG_SUBCATEGORIES: Record<number, { id: number; label: string }[]> = {
    2701: [
        { id: 2853, label: "FI TRANSACTION" },
        { id: 2854, label: "FI REPORTS" },
        { id: 2855, label: "FI PRINT RELATED ISSUES" },
        { id: 2856, label: "FI INTEGRATION RELATED ISSUES" },
        { id: 2969, label: "FI BATCH JOB SETUP" },
    ],
    2703: [
        { id: 3476, label: "MM TRANSACTION" },
        { id: 3477, label: "MM REPORTS" },
        { id: 3478, label: "MM PRINT RELATED ISSUES" },
        { id: 3479, label: "MM INTEGRATION RELATED ISSUES" },
        { id: 2791, label: "MM BATCH JOB SETUP" },
    ],
    2726: [
        { id: 23219, label: "WRICEF" },
        { id: 60539, label: "FIORI" },
        { id: 23221, label: "FORMS" },
        { id: 23223, label: "TECHNICAL ERROR" },
        { id: 23222, label: "CDS & AMDP" },
        { id: 23220, label: "ODATA & FIORI" },
    ],
    2847: [
        { id: 3452, label: "SD TRANSACTION" },
        { id: 3451, label: "SD BATCH JOB" },
        { id: 3453, label: "SD REPORTS" },
        { id: 3455, label: "SD INTEGRATION RELATED ISSUES" },
        { id: 3454, label: "SD PRINT RELATED ISSUES" },
    ],
    2848: [
        { id: 3460, label: "PP INTEGRATION RELATED ISSUES" },
        { id: 3456, label: "PP BATCH JOB SETUP" },
        { id: 3457, label: "PP TRANSACTION" },
        { id: 3458, label: "PP REPORTS" },
        { id: 3459, label: "PP PRINT RELATED ISSUES" },
    ],
    2849: [
        { id: 3462, label: "TM TRANSACTION" },
        { id: 3465, label: "TM INTEGRATION RELATED ISSUES" },
        { id: 3464, label: "TM PRINT RELATED ISSUES" },
        { id: 3463, label: "TM REPORTS" },
        { id: 3461, label: "TM BATCH JOB SETUP" },
    ],
    2850: [
        { id: 3467, label: "PM TRANSACTION" },
        { id: 3466, label: "PM BATCH JOB SETUP" },
        { id: 3469, label: "PM PRINT RELATED ISSUES" },
        { id: 3468, label: "PM REPORTS" },
        { id: 3470, label: "PM INTEGRATION RELATED ISSUES" },
    ],
    2851: [
        { id: 3474, label: "EWM PRINT RELATED ISSUES" },
        { id: 3475, label: "EWM INTEGRATION RELATED ISSUES" },
        { id: 3473, label: "EWM REPORTS" },
        { id: 3472, label: "EWM TRANSACTION" },
        { id: 3471, label: "EWM BATCH JOB SETUP" },
    ],
    2852: [
        { id: 34982, label: "BATCH JOB" },
        { id: 15442, label: "BASIS CONFIGURATION" },
        { id: 55162, label: "SAP SINGLE SIGN ON" },
        { id: 2966, label: "SAP GUI INSTALLTION" },
        { id: 53135, label: "AZURE CONFIGURATION" },
        { id: 15441, label: "BACKGROUND JOB" },
        { id: 15440, label: "ERROR ANALYSIS" },
        { id: 15439, label: "NOTE IMPLEMENTATION" },
    ],
    3421: [
        { id: 3430, label: "QM" },
        { id: 3431, label: "SF" },
        { id: 3422, label: "FI" },
        { id: 3529, label: "TM" },
        { id: 3423, label: "CO" },
        { id: 3429, label: "PP" },
        { id: 3425, label: "SD" },
        { id: 3426, label: "MM" },
        { id: 3427, label: "PM" },
        { id: 3428, label: "EWM" },
        { id: 3424, label: "TRM" },
    ],
    3976: [
        { id: 508121, label: "NEW REQUIREMENT" },
        { id: 508122, label: "REPLICATION REQUEST" },
        { id: 508123, label: "PAYROLL RELATED ISSUE" },
        { id: 508124, label: "SUCCESS FACTORS RELATED ISSUE" },
        { id: 508125, label: "REPORT RELATED" },
    ],
    4458: [
        { id: 246353, label: "ROLE CREATION / UPDATE" },
        { id: 5201, label: "AUTHORISATION ISSUE" },
        { id: 2961, label: "CREATION OF SAP USER" },
        { id: 55163, label: "MODIFICATION OF SAP USER" },
        { id: 258190, label: "MISCELLANEOUS REQUESTS" },
        { id: 258184, label: "FF ID ACCESS" },
        { id: 258185, label: "INACTIVITY USERS REPORT EXECUTION AND REVIEW ON SAP SYSTEMS" },
        { id: 258187, label: "USER SSO (SINGLE SIGN ON) ACCESS" },
        { id: 466084, label: "FIRE FIGHTER LOG REVIEW MONITORING" },
        { id: 466085, label: "ADDITIONAL ACCESS TO USERS" },
        { id: 466086, label: "FFID ADDITIONAL ACCESS OR DEBUG ACCESS" },
        { id: 246354, label: "TERMINATION OF USER" },
        { id: 246356, label: "DAILY MONITORING - CRITICAL ACCESS" },
        { id: 9923, label: "PASSWORD RESET" },
        { id: 246355, label: "SOD REPORTS - MONTHLY" },
    ],
    4462: [
        { id: 4468, label: "APP ACTIVATION" },
        { id: 4467, label: "SAP FIORI ACCESS ISSUE" },
        { id: 4466, label: "SAP FIORI ACCESS REQUEST" },
    ],
    4469: [
        { id: 4471, label: "QM INTEGRATION RELATED ISSUES" },
        { id: 4470, label: "QM TRANSACTION" },
    ],
    13185: [
        { id: 13190, label: "PP-PRODUCTION" },
        { id: 13189, label: "MM-MATERIAL MANAGEMENT" },
        { id: 13188, label: "SD-SALES" },
        { id: 13192, label: "PM-PLANT MANAGEMENT" },
        { id: 13193, label: "TM-TRANSPORT" },
        { id: 13187, label: "CO-COSTING" },
        { id: 13186, label: "FI-FINANCE" },
        { id: 13191, label: "QM-QUALITY" },
    ],
    18998: [
        { id: 21382, label: "EMAIL ID CREATION" },
        { id: 21387, label: "SYSTEM TROUBLESHOOTING" },
        { id: 21381, label: "VPN ID CREATION" },
        { id: 18999, label: "VPN INSTALL" },
    ],
    135435: [
        { id: 135439, label: "TRM1" },
    ],
    152838: [
        { id: 152882, label: "Apex Developemnt" },
    ],
    156494: [
        { id: 156496, label: "CO INTEGRATION" },
        { id: 156500, label: "CO ACTUAL COSTING" },
        { id: 156497, label: "CO REPORTS" },
        { id: 156498, label: "CO TRANSACTION" },
        { id: 156499, label: "CO STANDARD COSTING" },
        { id: 156495, label: "CO MASTER DATA" },
    ],
    287815: [
        { id: 445421, label: "APEX" },
    ],
};
